version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-sgc}
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - ./docker/DDL_SGC.sql:/docker-entrypoint-initdb.d/SGC.sql
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgress}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
    - "${PGADMIN_PORT:-8080}:80"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped
  
networks:
  postgres:
    driver: bridge

volumes:
  postgres_data: